# Generated by Django 4.2.1 on 2023-06-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
